### ISSUE TITLE
tzdata and the case of the missing pacificnew file

### ISSUE THREAD

**Issue by vforgione** [UrbanCCD-UChicago/plenario2#143]
I keep seeing this when running the tests:

```
18:38:34.898 [error] GenServer :tzdata_release_updater terminating
** (File.Error) could not stream "/home/travis/build/UrbanCCD-UChicago/plenario2/_build/test/lib/tzdata/priv/tmp_downloads/339626_44358462//pacificnew": no such file or directory
    (elixir) lib/file/stream.ex:83: anonymous fn/2 in Enumerable.File.Stream.reduce/3
    (elixir) lib/stream.ex:1337: anonymous fn/5 in Stream.resource/3
    (elixir) lib/stream.ex:1527: Enumerable.Stream.do_each/4
    (elixir) lib/enum.ex:1911: Enum.reverse/1
    (elixir) lib/enum.ex:2588: Enum.to_list/1
    (tzdata) lib/tzdata/parser.ex:16: Tzdata.Parser.process_file/1
    (tzdata) lib/tzdata/basic_data_map.ex:8: anonymous fn/2 in Tzdata.BasicDataMap.from_files_in_dir/1
    (elixir) lib/enum.ex:1294: Enum."-map/2-lists^map/1-0-"/2
    (elixir) lib/enum.ex:1294: Enum."-map/2-lists^map/1-0-"/2
    (tzdata) lib/tzdata/basic_data_map.ex:8: Tzdata.BasicDataMap.from_files_in_dir/1
    (tzdata) lib/tzdata/data_builder.ex:32: Tzdata.DataBuilder.do_load_and_save_table/4
    (tzdata) lib/tzdata/release_updater.ex:46: Tzdata.ReleaseUpdater.poll_for_update/0
    (tzdata) lib/tzdata/release_updater.ex:17: Tzdata.ReleaseUpdater.handle_info/2
    (stdlib) gen_server.erl:616: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:686: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Last message: :check_if_time_to_update
```

What's the deal here? Also, if this isn't on you @HeyZoos  then assign it back to me.

**Comment by HeyZoos** [comment]
Not sure what's causing this, but it doesn't fail the tests so maybe it's not a very vital service. I'll do a deep dive to see if I can fix whatever is causing it to shut down.

**Comment by HeyZoos** [comment]
The issue seems to have stopped appearing, we can reopen this if it becomes a problem again
