### ISSUE TITLE
We attempt ingests for datasets that haven't been approved

### ISSUE THREAD

**Issue by HeyZoos** [UrbanCCD-UChicago/plenario2#214]
The following log shows me creating a dataset, and before I can submit it for approval it is picked up for ingest.

```
17:14:52.092 request_id=efpri62e6km51u0r84nsgjmh0du31ecd [info] GET /data-sets/8/constraints/new
17:14:52.094 request_id=efpri62e6km51u0r84nsgjmh0du31ecd [info] Sent 200 in 1ms
17:14:56.154 request_id=d5hkm4t4ithinit3b8ff121d82sq9oi3 [info] POST /data-sets/8/constraints
17:14:56.158 request_id=d5hkm4t4ithinit3b8ff121d82sq9oi3 [info] Sent 302 in 3ms
17:14:56.191 request_id=oie2tejgpri0j24p3hf1tvhi8ii0jike [info] GET /data-sets/8 
17:14:56.197 request_id=oie2tejgpri0j24p3hf1tvhi8ii0jike [info] Sent 200 in 6ms
17:15:00.001 [info] [#PID<0.24536.0>] [refresh_datasets] time bounds: now=2018-03-06 17:15:00.001052Z last_check=2018-03-06 17:14:00.001052Z
17:15:00.002 [info] [#PID<0.24536.0>] [refresh_datasets] Refreshing 0 datasets: []
17:15:06.671 request_id=m1960hvkv46s95tqcjuj0lnequos14ml [info] GET /data-sets/8/virtual-points/new
17:15:06.673 request_id=m1960hvkv46s95tqcjuj0lnequos14ml [info] Sent 200 in 2ms
17:15:11.672 request_id=bvd14ktfv4a57r6bh4099f4pf9j4qqcj [info] POST /data-sets/8/virtual-points
17:15:11.676 request_id=bvd14ktfv4a57r6bh4099f4pf9j4qqcj [info] Sent 302 in 3ms
17:15:11.719 request_id=9suc6sac2lg0jcennemrn6lifv0ivrn2 [info] GET /data-sets/8 
17:15:11.726 request_id=9suc6sac2lg0jcennemrn6lifv0ivrn2 [info] Sent 200 in 7ms
17:15:14.981 request_id=9gseonivddopjsj7hbunkbh7504kf2g4 [info] GET /data-sets/8/virtual-dates/new
17:15:14.983 request_id=9gseonivddopjsj7hbunkbh7504kf2g4 [info] Sent 200 in 2ms
17:15:20.998 request_id=fmh1c68fdicggi3j9bh5flc4ha6e8n56 [info] GET /data-sets/8/
17:15:21.005 request_id=fmh1c68fdicggi3j9bh5flc4ha6e8n56 [info] Sent 200 in 6ms
17:15:29.158 request_id=sqp8btn86mh8c04uu5qshq771mjuph7e [info] GET /data-sets/8/edit
17:15:29.165 request_id=sqp8btn86mh8c04uu5qshq771mjuph7e [info] Sent 200 in 6ms
17:15:53.156 request_id=rke263bsfmnuaoafihsk8g87a096lsjc [info] POST /data-sets/8
17:15:53.159 request_id=rke263bsfmnuaoafihsk8g87a096lsjc [info] Sent 302 in 3ms
17:15:53.192 request_id=55ik9qu0q616skoqad0ujob6h42er355 [info] GET /data-sets/8 
17:15:53.199 request_id=55ik9qu0q616skoqad0ujob6h42er355 [info] Sent 200 in 6ms
17:16:00.001 [info] [#PID<0.24595.0>] [refresh_datasets] time bounds: now=2018-03-06 17:16:00.000984Z last_check=2018-03-06 17:15:00.000984Z
17:16:00.002 [info] [#PID<0.24595.0>] [refresh_datasets] Refreshing 1 datasets: ["City of Chicago, 311 Serivce Requests for Tree Trimmings"]
17:16:00.006 [info] [#PID<0.2218.0>] [handle_call] Received :load call
17:16:00.008 [info] [#PID<0.2218.0>] [load] Downloading file for City of Chicago, 311 Serivce Requests for Tree Trimmings
17:16:00.008 [info] [#PID<0.2218.0>] [load] City of Chicago, 311 Serivce Requests for Tree Trimmings source url is http://data.cityofchicago.org/api/views/uxic-zsuj/rows.csv?accessType=DOWNLOAD
17:16:00.008 [info] [#PID<0.2218.0>] [load] City of Chicago, 311 Serivce Requests for Tree Trimmings source type is csv
17:16:00.008 [info] [#PID<0.2218.0>] [load] Using constraints [:Location]
17:16:02.124 request_id=5ne54o8198hn0l7c88mpo0go67k6mpal [info] POST /data-sets/8/submit-for-approval
17:16:02.127 request_id=5ne54o8198hn0l7c88mpo0go67k6mpal [info] Sent 302 in 3ms
17:16:02.172 request_id=dccmd3jt6abutsmd085tnal8o5og8pr3 [info] GET /data-sets/8 
17:16:02.179 request_id=dccmd3jt6abutsmd085tnal8o5og8pr3 [info] Sent 200 in 7ms
17:16:02.224 request_id=0i24ui5gfaugscablnukptls1c01j0rr [info] POST /data-sets/8/submit-for-approval
17:16:02.226 request_id=0i24ui5gfaugscablnukptls1c01j0rr [info] Sent 302 in 1ms
17:16:02.255 request_id=22d40kpfi2ba13sd12uvjonejf6j5sj8 [info] GET /data-sets/8 
17:16:02.261 request_id=22d40kpfi2ba13sd12uvjonejf6j5sj8 [info] Sent 200 in 6ms
17:16:32.136 [info] [#PID<0.2218.0>] [load] File stored at /tmp/ds_3RMsB2dvM-ve333z.csv
17:16:32.136 [info] [#PID<0.2218.0>] [load_csv] Prep loader for csv at /tmp/ds_3RMsB2dvM-ve333z.csv
17:16:32.136 [info] [#PID<0.2218.0>] [load_data] Chunking rows and spawning children
17:16:32.147 [info] [#PID<0.2218.0>] [load_chunk] Running contains query
17:16:32.188 [error] GenServer #PID<0.2218.0> terminating
** (Postgrex.Error) ERROR 42P01 (undefined_table): relation "ds_3RMsB2dvM-ve333z" does not exist
    (ecto) lib/ecto/adapters/sql.ex:431: Ecto.Adapters.SQL.execute_and_cache/7
    (ecto) lib/ecto/repo/queryable.ex:133: Ecto.Repo.Queryable.execute/5
    (ecto) lib/ecto/repo/queryable.ex:37: Ecto.Repo.Queryable.all/4
    (plenario) lib/plenario_etl/worker.ex:100: PlenarioEtl.Worker.load_chunk!/4
    (elixir) lib/enum.ex:1298: anonymous fn/3 in Enum.map/2
    (elixir) lib/enum.ex:1911: anonymous fn/3 in Enum.map/2
    (elixir) lib/stream.ex:1515: anonymous fn/3 in Enumerable.Stream.reduce/3
    (elixir) lib/stream.ex:247: anonymous fn/4 in Stream.chunk_while_fun/2
```

**Comment by vforgione** [comment]
can you confirm this is still a problem after cutting the latest release?
